name: build-and-test
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag'
        required: true
        default: 'master'

jobs:

  checkout-tag:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          # https://github.com/actions/checkout/issues/217
          fetch-depth: 0
      - run: |
          git checkout ${{ github.event.inputs.tag }}
      
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "building package! (fake)"

  test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "testing! (fake)"

  create-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/create-an-issue@v2
        id: create-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_RUN_ID: ${{ env.GITHUB_RUN_ID }}
        with:
          filename: .github/issue.build-test.complete.md