name: build-and-test
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'tag'
        required: true
        default: 'master'

jobs:
  test2:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git checkout ${{ github.event.inputs.tag }}
          git tag
          git status
      
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello ${{ github.event.inputs.name }}!"
        echo "- in ${{ github.event.inputs.home }}!"
  test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello ${{ github.event.inputs.name }}!"
        echo "- in ${{ github.event.inputs.home }}!"