name: flow1

on: push

jobs:
  create-issue:
    name: create-issue

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8' 

      - name: setup-py
        run: |
          pip install virtualenv  

      - name: echo
        run: |
          echo "dog"

      - name: run-script
        id: run-script
        run: |
          python -m venv demo.ve
          source demo.ve/bin/activate
          pip install -r requirements.txt
          which python
          python ./demo.py dog

          EXIT_CODE=$?
          echo "::set-output name=run-script-exit-code::$EXIT_CODE"

      - uses: JasonEtco/create-an-issue@v2
        id: create-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEST_VAR: "howdy"
        with:
          filename: .github/ISSUE_TEMPLATE.md

      - run: 'echo Created issue number ${{ steps.create-issue.outputs.number }}'
      - run: 'echo Created ${{ steps.create-issue.outputs.url }}'
      - run: 'echo run-script exit-code ${{ steps.run-script.run-script-exit-code }}'