name: flow1

on: push

jobs:
  create-issue:
    name: create-issue

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: create issue
        run: |
          echo "dog"